name: Greet user action
description: Say hello to someone

inputs:
  greeting:
    description: "Greeting words"
    required: true
    type: string
    default: Hello
  name:
    description: "Someone's name"
    required: true
    type: string
    default: My friend
outputs:
  full-greeting:
    value: ${{steps.last-step.outputs.result}}

runs:
  using: "composite"
  steps:
    - name: Say hello
      run: echo "${{inputs.greeting}}, ${{inputs.name}}!"
      shell: bash
    - name: Generate output
      id: last-step
      env:
        RESULT: "${{inputs.greeting}}, ${{inputs.name}}!"
      run: echo "result=$RESULT" >> $GITHUB_OUTPUT
      shell: bash
